#!/bin/bash
# Main
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             first_child
yabai -m config window_topmost               on
yabai -m config split_ratio                  0.55
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config focus_follows_mouse          autoraise
# yabai -m config external_bar                 all:0:26
yabai -m config window_border_width          10
yabai -m config window_border                on
yabai -m config active_window_border_color   0xffea962
yabai -m config normal_window_border_color   0xff1d2021
yabai -m config layout                       bsp
yabai -m config top_padding                  40
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   6


# floating windows are always on top (default: off)
yabai -m config window_topmost on

# Create Sapce on focused windows
yabai -m space --create
yabai -m config auto_balance                off

# Sketchybar BS
yabai -m signal --add event=window_created action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=space_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger yabai_window &> /dev/null"

# Spaces
yabai -m space 1 --label Terminal
yabai -m space 2 --label Notes
yabai -m space 3 --label Files
yabai -m space 4 --label Browsers
yabai -m space 5 --label Music
yabai -m space 6 --label Office
yabai -m rule --add app="^iTerm2$" space=Terminal
yabai -m rule --add app="^Obsidian$" space=Notes
yabai -m rule --add app="^Finder$" space=Files
yabai -m rule --add app="^Firefox$" space=Browsers
yabai -m rule --add app="^Music$" space=Music
yabai -m rule --add app="^ONLYOFFICE$" space=Office
yabai -m rule --add app="^Goodnotes$" space=Notes

yabai -m signal --add event=space_changed action="node ~/.config/yabai/hammerspoon_bsp_helper.js"

yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'

# sketchybar &
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
