#!/usr/bin/env sh
#  ___
# |_ _| |_ __ _ _   _
#  | || __/ _` | | | |  github: https://github.com/itaysharir
#  | || || (_| | |_| |  reddit: u/visible-pop-2576
# |___|\__\__,_|\__, |  dotfiles: https://github.com/itaysharir/Dotfiles
#               |___/

### Load colors and icons ###
. "$HOME/.config/sketchybar/colors.sh"  # Loads all defined colors
. "$HOME/.config/sketchybar/icons.sh"   # Loads all defined icons

### Store plugin and item directories in variables ###
ITEM_DIR="$HOME/.config/sketchybar/items"       # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"   # Directory where all the plugin scripts are stored

### Define space click script ###
export SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null"

### Define defult font ###
FONT="JetBrainsmono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

### Padding ###
PADDINGS=3          # All elements use this padidng (Wherever i didn't need it, I used negetive padding)
SEGMENT_SPACING=13  # The spacing between segments

### Setting up the general bar appearance and default values ###
sketchybar --bar     height=27.5                                                     \
                     corner_radius=0                                               \
                     border_width=0                                                \
                     margin=0                                                      \
                     blur_radius=12                                                 \
                     position=top                                                  \
                     padding_left=4                                                \
                     padding_right=4                                               \
                     color=$BAR_COLOR                                              \
                     topmost=off                                                   \
                     sticky=on                                                     \
                     font_smoothing=on                                             \
                     y_offset=-100                                                    \
                     notch_width=0                                                 \
                                                                                   \
           --default drawing=on                                                    \
                     updates=when_shown                                            \
                     label.font="FONT:Bold:15.0"                                   \
                     icon.font="$FONT:Bold:16.0"                                   \
                     icon.color=$ICON_COLOR                                        \
                     label.color=$LABEL_COLOR                                      \
                     icon.padding_left=$PADDINGS                                   \
                     icon.padding_right=$PADDINGS                                  \
                     label.padding_left=$PADDINGS                                  \
                     label.padding_right=$PADDINGS                                 \
                     background.padding_right=$PADDINGS                            \
                     background.padding_left=$PADDINGS                             \

sketchybar --animate sin 30 --bar y_offset=-100 y_offset=0

### Template for some elements ###
sketchybar --add item           label_template left                                \
           --set label_template icon.drawing=off                                   \
                                label.font="$FONT:Black:24.0"                      \
                                label.padding_right=5                              \
                                click_script="$PLUGIN_DIR/toggle_bracket.sh"       \
                                background.padding_left=$SEGMENT_SPACING           \
                                drawing=off                                        \

### Spaces themselves are this ###
. "$ITEM_DIR/spaces.sh"

### First Seperator on the bar ###
sketchybar   --add item       separator left                                       \
             --set separator  icon=┃                                               \
                              icon.font="JetBrainsmono Nerd Font:Regular:18.0"               \
                              background.padding_left=-5                           \
                              background.padding_right=-7                          \
                              icon.y_offset=2                                      \
                              label.drawing=off                                    \
                              icon.color=0xff606060

### BSP/float/stack/fullscreen text ###
sketchybar --add       event          window_focus                                 \
           --add       item           system.yabai left                            \
           --set       system.yabai   script="$PLUGIN_DIR/yabai.sh"                \
                                      icon.font="$FONT:Bold:16.0"                  \
                                      label.drawing=off                            \
                                      icon.color=$BLACK                            \
                                      icon.y_offset=2                              \
                                      icon.padding_left=8                          \
                                      updates=on                                   \
           --subscribe system.yabai window_focus mouse.clicked                     \

### Second seperator on the bar ###
# sketchybar   --add item        separator2 left                                     \
#              --set separator2  icon=┃                                              \
#                                icon.font="Hack Nerd Font:Regular:13.5"              \
#                                background.padding_right=0                          \
#                                background.padding_left=-3                          \
#                                icon.y_offset=1                                     \
#                                label.drawing=off                                   \
#                                icon.color=0xff606060                               \
### Space number ###
# . "$ITEM_DIR/spacenum.sh"

### Third seperator on the bar ###
# sketchybar   --add item       separator3 left                                      \
#              --set separator3  icon=┃                                              \
#                               icon.font="Hack Nerd Font:Regular:13.5"               \
#                               background.padding_right=-5                          \
#                               icon.y_offset=1                                      \
#                               label.drawing=off                                    \
#                               icon.color=0xff606060                                \

# Curent procces name
# sketchybar --add       event        window_focus                                   \
#            --add       event        title_change                                   \
#            --add       item         window_title left                              \
#            --set       window_title script="$PLUGIN_DIR/window_title.sh"           \
#                                     label.font="$FONT:Bold:14.8"                   \
#                                     label.y_offset=2                               \
#                                     label.padding_left=-0                          \
#                                     label.color=0xff1d2021                         \
#            --subscribe window_title window_focus title_change                      \

### Menu bar items ###
. "$ITEM_DIR/system.sh"

### Time Widget ###
sketchybar --add item clock right                                                  \
           --set clock update_freq=1                                               \
                       icon=""                                                   \
                       icon.font="Font Awesome 6 Free:Solid:12.4"                  \
                       icon.padding_right=4                                        \
                       icon.color=$ORANGE\
                       icon.y_offset=2                                             \
                       label.y_offset=2                                            \
                       label.font="$FONT:Bold:11.8"                                \
                       label.color=$ORANGE\
                       label.padding_right=8                                       \
                       background.color=$ORANGE \
                       background.height=2                                         \
                       background.padding_right=6                                  \
                       background.y_offset=-9                                      \
                       script="$PLUGIN_DIR/clock.sh"                               \
                       icon.padding_left=0 label.padding_right=1                   \

### Battery Widget ###
sketchybar --add item battery right                                                \
           --set battery update_freq=2                                             \
                       icon.font="Font Awesome 6 Free:Solid:12.4"                  \
                       icon.padding_right=3                                        \
                       icon.color=$YELLOW\
                       icon.y_offset=2                                             \
                       label.y_offset=1                                            \
                       label.font="$FONT:Bold:11.4"                                \
                       label.color=$YELLOW\
                       label.padding_right=8                                       \
                       background.color=$YELLOW\
                       background.height=2                                         \
                       background.y_offset=-9                                      \
                       background.padding_right=8                                  \
                       script="$PLUGIN_DIR/battery.sh"                             \
                       icon.padding_left=0 label.padding_right=0                   \

### Updates Widget ###
# sketchybar --add item updates right                                                \
#            --set updates update_freq=1800                                          \
#                        icon=""                                                   \
#                        icon.font="Font Awesome 6 Free:Solid:12.4"                  \
#                        icon.padding_right=7                                        \
#                        icon.color=0xffe78a4e \
#                        icon.y_offset=1                                             \
#                        label.y_offset=1                                            \
#                        label.font="$FONT:Bold:11.6"                                \
#                        label.color=0xffe78a4e                                     \
#                        label.padding_right=8                                       \
#                        background.color=0xffe78a4e\
#                        background.height=2                                         \
#                        background.y_offset=-9                                      \
#                        background.padding_right=8                                  \
#                        script="$PLUGIN_DIR/package_monitor.sh"                     \
#                        icon.padding_left=0 label.padding_right=2                   \
### Uptime Widget ###
# sketchybar --add item uptime right                                                 \
#            --set uptime update_freq=120                                            \
#                        icon.font="Font Awesome 6 Free:Solid:12.4"                  \
#                        icon.padding_right=4                                        \
#                        icon.color=0xffa9b665\
#                        label.y_offset=1                                            \
#                        icon.y_offset=1                                             \
#                        label.font="$FONT:Bold:11.6"                                \
#                        label.color=0xffa9b665\
#                        label.padding_right=8                                       \
#                        background.color=0xffa9b665\
#                        background.height=2                                         \
#                        background.y_offset=-9                                      \
#                        background.padding_right=8                                  \
#                        script="$PLUGIN_DIR/uptime.sh"                              \
#                        icon.padding_left=0 label.padding_right=2                   \
### ssd Widget ###
sketchybar --add item  ssd right                                                   \
           --set ssd   update_freq=10                                              \
                       icon.font="Font Awesome 6 Free:Solid:13.3"                  \
                       icon.padding_right=4                                        \
                       icon.color=0xffd3869b \
                       icon.y_offset=1                                             \
                       label.y_offset=1                                            \
                       label.font="$FONT:Bold:11.6"                                \
                       label.color=0xffd3869b\
                       label.padding_right=8                                       \
                       background.color=0xffd3869b \
                       background.height=2                                         \
                       background.y_offset=-9                                      \
                       background.padding_right=8                                  \
                       script="$PLUGIN_DIR/disk.sh"                                \
                       icon.padding_left=0 label.padding_right=2                   \

### mem Widget ###
sketchybar --add item  mem right                                                   \
           --set mem   update_freq=1                                              \
                       icon.font="Font Awesome 6 Free:Solid:13.3"                  \
                       icon.padding_right=4                                        \
                       icon.color=0xff89b482\
                       icon.y_offset=1                                             \
                       label.y_offset=1                                            \
                       label.font="$FONT:Bold:11.6"                                \
                       label.color=0xff89b482\
                       label.padding_right=8                                       \
                       background.color=0xff89b482 \
                       background.height=2                                         \
                       background.y_offset=-9                                      \
                       background.padding_right=8                                  \
                       script="$PLUGIN_DIR/mem.sh"                                 \
                       icon.padding_left=0 label.padding_right=2                   \

### cpu Widget ###
sketchybar --add item  cpu right                                                   \
           --set cpu   update_freq=1                                              \
                       icon.font="Font Awesome 6 Free:Solid:12.4"                  \
                       icon.padding_right=4                                        \
                       icon.color=0xff7daea3 \
                       icon.y_offset=1                                             \
                       label.y_offset=1                                            \
                       label.font="$FONT:Bold:11.6"                                \
                       label.color=0xff7daea3 \
                       label.padding_right=8                                       \
                       background.color=0xff7daea3 \
                       background.height=2                                         \
                       background.y_offset=-9                                      \
                       background.padding_right=8                                  \
                       script="$PLUGIN_DIR/cpu.sh"                                 \
                       icon.padding_left=0 label.padding_right=2                   \

### os version Widget ###
# sketchybar --add item  ver right                                                   \
#            --set ver   update_freq=6400                                            \
#                        icon.font="Font Awesome 6 Brands:Regular:12.4"              \
#                        icon.padding_right=4                                        \
#                        icon.color=0xff88b3d8                                       \
#                        icon.y_offset=1                                             \
#                        label.y_offset=1                                            \
#                        label.font="$FONT:Bold:11.6"                                \
#                        label.color=0xff88b3d8                                      \
#                        label.padding_right=8                                       \
#                        background.color=0xff88b3d8                                 \
#                        background.height=2                                         \
#                        background.y_offset=-9                                      \
#                        background.padding_right=8                                  \
#                        script="$PLUGIN_DIR/os-ver.sh"                              \
#                        icon.padding_left=-1 label.padding_right=2                  \

### If an update is avalible, update sketchybar when launched ##
sketchybar --update

### Notify when sketchybarrc is finished loading ##
echo "sketchybar configuation loaded.."
