#!/bin/sh
# Colors
bar=(
  color=0xff282828
  height=20
  sticky=on
  padding_left=7
  padding_right=7
  font_smoothing=on
)

default=(
  icon.drawing=off
  label.padding_left=4
  label.padding_right=4
  label.color=0xffa89984
)

sketchybar \
  --bar "${bar[@]}" \
  --default "${default[@]}"

sketchybar \
  --add item space left \
  --set space script='sketchybar --set $NAME label="[$(echo "$INFO" | jq .[])]"'\
  --subscribe space space_change


sketchybar \
  --add item app_name left \
  --set app_name script='sketchybar --set $NAME label="[$USER@$INFO]"' \
  --subscribe app_name front_app_switched

sketchybar \
  --add item time right \
  --set time script='sketchybar --set $NAME label="$(date "+%r")"' \
             update_freq=1 \
  --subscribe time system_woke

sketchybar \
  --add item ip right \
  --set ip script='sketchybar --set $NAME label="/$(ipconfig getifaddr en0)/"'\
  --subscribe ip wifi_change

sketchybar --update
