$wallpaper = /home/kvl/gowallConvertions/WallpapersGruvbox/cosmic-light-trails-2560x1080-20467.jpg
$background = #000000
$foreground = #ffffff
$color0 = 413731
$color1 = ff943a
$color2 = ff9b47
$color3 = ffa254
$color4 = ffa961
$color5 = ffb06d
$color6 = ffb77a
$color7 = d6c3b6
$color8 = 51443b
$color9 = ffb782
$color10 = ffbf8f
$color11 = ffc69c
$color12 = ffcda8
$color13 = ffd5b5
$color14 = ffdcc2
$color15 = efe0d6

$primary = ffb77a
$secondary = e3c0a5
$tertiary = c4cb97
$surface = #000000
$surface_bright = 413731
$error = ff5945
