source = ./source/monitor.conf
source = ./source/variable.conf
source = ./source/colors.conf
source = ./source/autostart.conf
source = ./source/animations.conf
source = ./source/env.conf
source = ./source/rules.conf
source = ./source/general.conf
source = ./source/input.conf
source = ./source/decoration.conf
source = ./source/misc.conf

$mainMod = SUPER
$VimEnter = SUPER, Escape
$SitesEnter = SUPER, W
$runEnter = SUPER, R

source = ./source/hyprhook.conf
bindd = SUPER, I,+ Insert Mode, exec, echo "Insert Mode" > ~/.config/hypr/mode.txt
bind = SUPER, Escape, exec, echo "Normal Mode" > ~/.config/hypr/mode.txt
bind = SUPER, W, exec, echo "Site Mode" > ~/.config/hypr/mode.txt;~/.config/hypr/whichkey/whichkey.sh site
bind = SUPER, R, exec, echo "Run Mode" > ~/.config/hypr/mode.txt;~/.config/hypr/whichkey/whichkey.sh run

source = ./source/normalMode.conf
source = ./source/runMode.conf
source = ./source/siteMode.conf
source = ./source/insertMode.conf
source = ./source/master.conf
# source = ./source/hyprscroller.conf
bindd = $mainMod, M, Toggle Binds Help, exec, ~/.config/hypr/scripts/which-key.sh -b
