[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class kitty-dropterm"

[scratchpads.term]
animation = "fromTop"
command = "kitty -c ~/.config/kitty/kitty-hypr.conf --class kitty-dropterm"
class = "kitty-dropterm"
size = "85% 80%"
max_size = "1920px 100%"
margin = 50

[scratchpads.pulsemixer]
animation = "fromRight"
command = "kitty --class kitty-dropterm pulsemixer"
size = "85% 80%"
max_size = "1920px 100%"
margin = 50

[scratchpads.volume]
animation = "fromBottom"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true
