#!/bin/zsh

alias cl="clear" 
alias cc="cd ~/.clones"
alias cd.="cd ~/.config"
alias gc="git clone --depth 1"
alias off="echo 0 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias on="echo 100000 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias shit="sudo shutdown now"
alias fucked="sudo systemctl suspend"
alias live="sudo auto-cpufreq --live"
alias aud="alsamixer"
alias remove="sudo pacman -Rns"
alias ls='exa -al --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias sudoedit="sudo nvim"
alias nv="nvim"
alias rmf="rm -rf"
alias srmf="sudo rm -rf"
alias re="sudo reboot"
alias car="cargo run"
alias dnf="sudo dnf"
alias cool="sudo intel-undevolt apply"
alias chadwm="startx ~/.local/bin/run.sh"
alias showpic="kitty +kitten icat"
