exec-once = waybar &
# exec-once = ~/.config/ags/vim_styled &
exec-once = pypr &
exec-once = swww-daemon &
exec-once = nm-applet &
exec-once = hyprctl setcursor macOS-White 23 &
exec-once = hyprpm reload -n &
exec-once = ~/src/hyprmodes/target/debug/hyprmodes &
# exec-once = ~/.local/bin/hypr-modes.sh &
# exec-once = $IMAGE=$(find ~/Wallpapers | shuf -n1); while true;do;sleep 300;matugen image $IMAGE;done &
# exec-once = hypridle &
# exec-once = waybar & hyprpaper & firefox
