$wallpaper = lukeSmith.jpg
$background = #000000
$foreground = #ffffff
$color0 = 393a31
$color1 = aebb4d
$color2 = b2bf56
$color3 = b6c25f
$color4 = bbc669
$color5 = bfc972
$color6 = c3cd7b
$color7 = c8c7b7
$color8 = 47483b
$color9 = cfde60
$color10 = d2e06b
$color11 = d5e275
$color12 = d9e580
$color13 = dce78a
$color14 = dfe995
$color15 = e5e3d6

$primary = c3cd7b
$secondary = c7c9a7
$tertiary = a2d0c1
$surface = #000000
$surface_bright = 393a31
$error = ff5945
