bind = $runEnter, submap, Run

submap = Run

$reset = hyprctl dispatch submap reset && echo "Insert Mode" > ~/.config/hypr/mode.txt &&

bindd = , I, Reset submap, exec, echo "Insert Mode" > ~/.config/hypr/mode.txt
bindd = , I, Reset submap, submap, reset
bindd = , Escape, Normal Mode, exec, echo "Normal Mode" > ~/.config/hypr/mode.txt
bindd = , Escape, Normal Mode, submap, Normal
bindd = , S, Site Mode, exec, echo "Site Mode" > ~/.config/hypr/mode.txt
bindd = , S, Site Mode, submap, Sites

bindd = , RETURN, Open Terminal, exec, $terminal -c ~/.config/kitty/kitty-hypr.conf
bindd = , R, +Rofi Menu ,exec,$reset ~/.config/rofi/launchers/type-4/launcher.sh
bindd = , W, +Firefox ,exec, $browser
bindd = , f, +Pcmanfm ,exec, $fileManager
bindd = , C,+Kill Active, killactive
bindd = CTRL SHIFT,+Quit Hyprland , Q, exec, hyprctl dispatch exit

# Screenshot
bindd = , s, +Screenshot Region, exec, hyprshot $ScreenshotFlags -m output
bindd = SHIFT,+ Screenshot A Window, s, exec, hyprshot $ScreenshotFlags -m region

submap = reset
