bind = $SitesEnter, submap, Sites

submap = Sites

# bind = SUPER, I, submap, reset
# bind = SUPER, I, exec, echo "Insert Mode" > ~/.config/hypr/mode.txt

bindd = , I, Reset submap, exec, echo "Insert Mode" > ~/.config/hypr/mode.txt
bindd = , I, Reset submap, submap, reset

$reset = hyprctl dispatch submap reset && echo "Insert Mode" > ~/.config/hypr/mode.txt &&

bindd = , v, +Vision Ias Student Portal, exec, $browser https://visionias.in/student/student_home.php
bindd = , g, +Google Search ,exec, $browser https://google.com
bindd = , y, +Youtube ,exec, $browser https://youtube.com
bindd = , r, +Reddit ,exec, $browser https://reddit.com
bindd = , w, +Whatsapp ,exec, $browser https://web.whatsapp.com
bindd = , a, +College Student Portal,exec, $browser http://aryabhattacollege.in/Internet/Index.aspx
bindd = , m, +Google Mail,exec, $browser https://mail.google.com/mail/u/1/#inbox
bindd = , c, + Chess,exec, $browser https://www.chess.com/home

submap = reset
